"""initial migration

Revision ID: 41c86fd8794
Revises: None
Create Date: 2015-04-05 08:05:06.885691

"""

# revision identifiers, used by Alembic.
revision = '41c86fd8794'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
